name: "Frogbot Scan Pull Request"

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - "**"   # Run for ALL branches on every commit

permissions:
  pull-requests: write
  contents: read

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["*"]
    environment: frogbot

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jfrog/frogbot@v2
        env:
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_URL: ${{ secrets.JF_URL }}

          # Option A: Using Token (recommended)
          # JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # Option B: Using Username/Password
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

          JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}
          JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
          JF_WORKING_DIR: Server
